kind: Template
apiVersion: v1
metadata:
  name: ${NAME}
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app: ${NAME}
        deploymentconfig: ${NAME}
      strategy:
        activeDeadlineSeconds: 21600
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        type: Recreate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: ${NAME}
            deploymentconfig: ${NAME}
        spec:
          containers:
            - env:
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: MINIO_BCGOVS3_ACCESS_KEY
                      name: minio-bcgovs3-keys
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      key: MINIO_BCGOVS3_SECRET_KEY
                      name: minio-bcgovs3-keys
                - name: MINIO_MODE
                  value: gateway s3 https://nrs.objectstore.gov.bc.ca
                - name: MINIO_DATA_DIR
                  value: ''
              image: ''
              imagePullPolicy: Always
              name: ${NAME}
              ports:
                - containerPort: 9000
                  protocol: TCP
              resources:
                limits:
                  cpu: 150m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 128Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              name: "${IMAGESTREAM}"
              namespace: "${NAMESPACE}"
          type: ImageChange
        - type: ConfigChange
    metadata:
      annotations:
        description: Defines how to deploy the minio server
      generation: 1
      labels:
        app: ${NAME}
      name: ${NAME}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: minio-bcgovs3-keys
      labels:
        app: "${NAME}"
    stringData:
      MINIO_BCGOVS3_ACCESS_KEY: "${MINIO_BCGOVS3_ACCESS_KEY}"
      MINIO_BCGOVS3_SECRET_KEY: "${MINIO_BCGOVS3_SECRET_KEY}"
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: 9000-tcp
          port: 9000
          protocol: TCP
          targetPort: 9000
      selector:
        deploymentconfig: ${NAME}
      sessionAffinity: None
      type: ClusterIP
    metadata:
      annotations:
        description: Exposes the minio server
      labels:
        app: ${NAME}
      name: ${NAME}
  - apiVersion: route.openshift.io/v1
    kind: Route
    spec:
      port:
        targetPort: 9000-tcp
      tls:
        termination: edge
      to:
        kind: Service
        name: ${NAME}
        weight: 100
      wildcardPolicy: None
    metadata:
      annotations:
        openshift.io/host.generated: 'true'
      labels:
        app: ${NAME}
      name: ${NAME}
parameters:
- name: NAME
  displayName: Name to apply to objects in the template
  value: cap-minio-eagle-dev-bcgovs3
  required: true
- name: IMAGESTREAM
  displayName: Minio image to deploy
  value: minio:latest
  required: true
- name: NAMESPACE
  displayName: Project name where image resides
  value: oabrei-tools
  required: true
- name: MINIO_BCGOVS3_ACCESS_KEY
  displayName: Minio BCGov S3 access key
  generate: expression
  from: "[a-zA-Z0-9]{8}"
  required: true
- name: MINIO_BCGOVS3_SECRET_KEY
  displayName: Minio BCGov S3 secret key
  generate: expression
  from: "[a-zA-Z0-9]{16}"
  required: true