kind: Template
apiVersion: v1
metadata:
  name: minio-benchmark
  creationTimestamp: 
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ubuntu
    creationTimestamp: 
    labels:
      shared: 'true'
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: '16.04'
      annotations: 
      from:
        kind: DockerImage
        name: ubuntu:16.04
      importPolicy: {}
      referencePolicy:
        type: Source
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    creationTimestamp: 
    labels:
      shared: 'true'
    annotations:
      description: Keeps track of changes in the application image
  spec:
    lookupPolicy:
      local: false
    tags: []
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
      buildconfig: "${NAME}"
  spec:
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${GIT_REF}"
      contextDir: "${SOURCE_CONTEXT_DIR}"
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ubuntu:16.04
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:${VERSION}"
    completionDeadlineSeconds: 600
    triggers:
    - type: ConfigChange
    - type: ImageChange
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the objects defined in this template.
  required: true
  value: minio-benchmark
- name: SOURCE_REPOSITORY_URL
  displayName: Git Repo URL
  description: The URL to the Git repository.
  required: true
  value: https://github.com/bcgov/cap-eagle-helper-pods.git
- name: VERSION
  required: true
  value: 'stable'
- name: GIT_REF
  displayName: Git Reference
  description: The git reference or branch.
  required: true
  value: master
- name: SOURCE_CONTEXT_DIR
  displayName: Source Context Directory
  description: The source context directory.
  required: false
  value: docker-images/minio-benchmark